version: "3"
services:
  localstack:
    container_name: "LocalStack"
    image: localstack/localstack:latest
    ports:
      - "4566:4566" # Edge Port
      - "4572:4572" # S3 Port
    environment:
      - SERVICES:s3
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - ./scripts/localstack:/docker-entrypoint-initaws.d

  main-service:
    container_name: "main-service"
    image: main-service:latest
    ports:
      - "9090:9090"
    depends_on:
      - postgres
      - localstack

  message-service:
    container_name: "message-service"
    image: message-service:latest
    ports:
      - "9091:9091"
    depends_on:
      - postgres
      - localstack
      - main-service

  postgres:
    image: "postgres:13.4-alpine"
    container_name: "postgres"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "social_network"
    ports:
      - "35432:5432"
#    volumes:
#      - ./scripts:/docker-entrypoint-initaws.d
