spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/social_network
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
salt: SALT

management:
  endpoints:
    web:
      exposure:
        include: '*'
