spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
    url: jdbc:postgresql://localhost:35432/social_network

salt: SALT

aws:
  region: "us-east-1"
  s3:
    endpoint: http://localhost:4566

management:
  endpoints:
    web:
      exposure:
        include: '*'
